Repository googleapis/java-gcloud-maven-plugin, pull requests merged in 2021-02, with the labels that each got.

#104 chore: remove samples
  .github/workflows/samples.yaml
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  synth.py
Labels: cla: yes, samples

#107 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full

#110 deps: pin commons-io to 2.6 for jdk 7 compatibility
  pom.xml
  renovate.json
Labels: cla: yes
